const STORAGE_KEY='minerva-executive-selection-v2';
const initialState={jobTitle:'Gerente Executivo',owner:'Talent Acquisition',currentStage:2,stages:[
 {id:'alignment',title:'Abertura e alinhamento',date:'14/08/2026',summary:'Realizado',notes:'Abertura da vaga e alinhamento do perfil com a liderança.',dateSlots:false,interviews:[],candidates:[]},
 {id:'hunting',title:'Publicação e hunting',date:'',summary:'',notes:'',dateSlots:false,interviews:[],candidates:[]},
 {id:'screening',title:'Triagem e mapeamento',date:'10/08/2026',summary:'30 cddts',notes:'30 candidatos mapeados para avaliação inicial.',dateSlots:false,interviews:[],candidates:[]},
 {id:'hub-interview',title:'Entrevista Hub de Seleção',date:'',summary:'',notes:'',dateSlots:true,interviews:[''],candidates:[]},
 {id:'manager-interview',title:'Entrevista gestor',date:'',summary:'',notes:'',dateSlots:true,interviews:[''],candidates:[]},
 {id:'bp-interview',title:'Entrevista BP',date:'',summary:'',notes:'',dateSlots:true,interviews:[''],candidates:[]},
 {id:'head-interview',title:'Head de Seleção',date:'',summary:'',notes:'',dateSlots:true,interviews:[''],candidates:[]},
 {id:'compliance',title:'Compliance',date:'',summary:'',notes:'',dateSlots:false,interviews:[],candidates:[]},
 {id:'senior-manager-interview',title:'Gestor do gestor',date:'',summary:'',notes:'',dateSlots:true,interviews:[''],candidates:[]},
 {id:'assessment',title:'Assessment',date:'',summary:'',notes:'',dateSlots:false,interviews:[],candidates:[]},
 {id:'committee',title:'Decisão em comitê',date:'',summary:'',notes:'',dateSlots:false,interviews:[],candidates:[]},
 {id:'proposal',title:'Proposta',date:'',summary:'',notes:'',dateSlots:false,interviews:[],candidates:[]},
 {id:'admission',title:'Processo Admissional',date:'',summary:'',notes:'',dateSlots:false,interviews:[],candidates:[]}
]};
let state=loadState();
const rail=document.querySelector('#stageRail'),workspace=document.querySelector('#stageWorkspace');
const clone=o=>JSON.parse(JSON.stringify(o));
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return saved?.stages?.length===13?saved:clone(initialState)}catch{return clone(initialState)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function escapeHtml(v=''){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderRail(){rail.innerHTML=state.stages.map((s,i)=>`<button class="stage-button ${i===state.currentStage?'active':''}" role="tab" aria-selected="${i===state.currentStage}" data-stage="${i}"><span class="stage-copy"><span class="stage-title">${escapeHtml(s.title)}</span><span class="stage-date">${escapeHtml(s.date)||'Data a definir'}</span>${s.summary?`<span class="stage-summary">${escapeHtml(s.summary)}</span>`:''}</span><span class="lamp-wrap"><span class="lamp-number">${String(i+1).padStart(2,'0')}</span><span class="lamp"></span></span></button>`).join('');rail.querySelectorAll('.stage-button').forEach(b=>b.onclick=()=>{state.currentStage=Number(b.dataset.stage);save();render()})}
function renderWorkspace(){const s=state.stages[state.currentStage];const isInterview=s.dateSlots;workspace.innerHTML=`<div class="workspace-header"><div><span class="eyebrow">Etapa ${String(state.currentStage+1).padStart(2,'0')} de 13</span><h2>${escapeHtml(s.title)}</h2></div><span class="status-pill">● Etapa atual</span></div><div class="workspace-grid"><div class="editor-card"><label class="field"><span>Data da etapa</span><input id="stageDate" placeholder="dd/mm/aaaa" value="${escapeHtml(s.date)}"></label><label class="field"><span>Registro da etapa</span><textarea id="stageNotes" placeholder="Escreva aqui decisões, status e próximos passos...">${escapeHtml(s.notes)}</textarea></label>${isInterview?`<div><span class="panel-label">Datas de entrevistas</span><div id="interviewDates">${s.interviews.map((d,i)=>`<div class="interview-row"><input type="datetime-local" value="${escapeHtml(d)}" data-interview="${i}" aria-label="Data da entrevista ${i+1}"><button class="icon-button remove-interview" data-remove-interview="${i}" aria-label="Remover data">×</button></div>`).join('')}</div><button id="addInterview" class="add-button">＋ Adicionar outra data de entrevista</button></div>`:''}<p class="save-note">Alterações salvas automaticamente neste dispositivo.</p></div><div class="candidates-panel"><div class="panel-label">Candidatos</div><div id="candidateList" class="candidate-list"></div><button id="addCandidate" class="add-button">＋ Adicionar candidato</button></div></div>`;
 document.querySelector('#stageDate').oninput=e=>{s.date=e.target.value;save();renderRail()};document.querySelector('#stageNotes').oninput=e=>{s.notes=e.target.value;save()};document.querySelector('#addCandidate').onclick=()=>{s.candidates.push({name:'',link:'',status:'active'});save();renderCandidates()};
 if(isInterview){document.querySelector('#addInterview').onclick=()=>{s.interviews.push('');save();renderWorkspace()};document.querySelectorAll('[data-interview]').forEach(el=>el.oninput=e=>{s.interviews[Number(e.target.dataset.interview)]=e.target.value;save()});document.querySelectorAll('[data-remove-interview]').forEach(el=>el.onclick=()=>{s.interviews.splice(Number(el.dataset.removeInterview),1);save();renderWorkspace()})}renderCandidates();}
function renderCandidates(){const s=state.stages[state.currentStage],list=document.querySelector('#candidateList');if(!s.candidates.length){list.innerHTML='<div class="empty-state">Nenhum candidato nesta etapa.<br>Use o botão abaixo para começar.</div>';return}list.innerHTML='';s.candidates.forEach((candidate,index)=>{const node=document.querySelector('#candidateTemplate').content.cloneNode(true),card=node.querySelector('.candidate-card'),name=node.querySelector('.candidate-name'),link=node.querySelector('.candidate-link'),open=node.querySelector('.linkedin-open');name.value=candidate.name;link.value=candidate.link;open.href=candidate.link||'#';open.style.opacity=candidate.link?'1':'.35';if(candidate.status==='rejected'){card.classList.add('rejected');card.querySelector('.advance').remove();card.querySelector('.reject').remove();name.disabled=link.disabled=true}name.oninput=e=>{candidate.name=e.target.value;save()};link.oninput=e=>{candidate.link=e.target.value;open.href=e.target.value||'#';open.style.opacity=e.target.value?'1':'.35';save()};open.onclick=e=>{if(!candidate.link)e.preventDefault()};card.querySelector('.advance')?.addEventListener('click',()=>advanceCandidate(index));card.querySelector('.reject')?.addEventListener('click',()=>{candidate.status='rejected';save();renderCandidates()});list.appendChild(node)})}
function advanceCandidate(index){if(state.currentStage>=state.stages.length-1)return;const [candidate]=state.stages[state.currentStage].candidates.splice(index,1);candidate.status='active';state.stages[state.currentStage+1].candidates.push(candidate);save();renderWorkspace()}
function bindSummary(){const title=document.querySelector('#jobTitle'),owner=document.querySelector('#owner');title.value=state.jobTitle;owner.value=state.owner;title.oninput=e=>{state.jobTitle=e.target.value;save()};owner.oninput=e=>{state.owner=e.target.value;save()}}
function render(){renderRail();renderWorkspace();bindSummary()}render();
