const STORAGE_KEY='minerva-executive-selection-v2';
const initialState={jobTitle:'Gerente Executivo',owner:'Talent Acquisition',currentStage:2,stages:[
 {id:'alignment',title:'Abertura e alinhamento',date:'14/08/2026',summary:'Realizado',notes:'Abertura da vaga e alinhamento do perfil com a liderança.',dateSlots:false,interviews:[],candidates:[]},
 {id:'hunting',title:'Publicação e hunting',date:'',summary:'',notes:'',dateSlots:false,interviews:[],candidates:[]},
 {id:'screening',title:'Triagem e mapeamento',date:'10/08/2026',summary:'30 cddts',notes:'30 candidatos mapeados para avaliação inicial.',dateSlots:false,interviews:[],candidates:[]},
 {id:'hub-interview',title:'Entrevista Hub de Seleção — Sonia',date:'',summary:'',notes:'',dateSlots:true,interviews:[''],candidates:[]},
 {id:'manager-interview',title:'Entrevista gestor',date:'',summary:'',notes:'',dateSlots:true,interviews:[''],candidates:[]},
 {id:'bp-interview',title:'Entrevista BP',date:'',summary:'',notes:'',dateSlots:true,interviews:[''],candidates:[]},
 {id:'compliance',title:'Compliance',date:'',summary:'',notes:'',dateSlots:false,interviews:[],candidates:[]},
 {id:'senior-manager-interview',title:'Gestor do gestor',date:'',summary:'',notes:'',dateSlots:true,interviews:[''],candidates:[]},
 {id:'assessment',title:'Assessment',date:'',summary:'',notes:'',dateSlots:false,interviews:[],candidates:[]},
 {id:'committee',title:'Decisão em comitê',date:'',summary:'',notes:'',dateSlots:false,interviews:[],candidates:[]},
 {id:'proposal',title:'Proposta',date:'',summary:'',notes:'',dateSlots:false,interviews:[],candidates:[]},
 {id:'admission',title:'Processo Admissional',date:'',summary:'',notes:'',dateSlots:false,interviews:[],candidates:[]}
]};
const clone=o=>JSON.parse(JSON.stringify(o));
function normalizeState(value){
 const next=value?.stages?clone(value):clone(initialState);
 const hub=next.stages.find(stage=>stage.id==='hub-interview');
 const head=next.stages.find(stage=>stage.id==='head-interview');
 if(hub){
  hub.title='Entrevista Hub de Seleção — Sonia';
  if(head){
   const existing=new Set(hub.candidates.map(candidate=>JSON.stringify(candidate)));
   head.candidates.forEach(candidate=>{if(!existing.has(JSON.stringify(candidate)))hub.candidates.push(candidate)});
  }
 }
 next.stages=next.stages.filter(stage=>stage.id!=='head-interview');
 next.stages.forEach(stage=>stage.candidates.forEach(candidate=>{if(typeof candidate.comments!=='string')candidate.comments=''}));
 next.currentStage=Math.min(Math.max(Number(next.currentStage)||0,0),next.stages.length-1);
 return next;
}
let state=loadState(),saveTimer=null,lastServerVersion=0,isHydrating=true;
const rail=document.querySelector('#stageRail'),workspace=document.querySelector('#stageWorkspace'),commentsDialog=document.querySelector('#commentsDialog'),commentsTextarea=document.querySelector('#candidateComments'),commentsName=document.querySelector('#commentsCandidateName');
let commentsCandidateIndex=null;
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return saved?.stages?normalizeState(saved):clone(initialState)}catch{return clone(initialState)}}
function candidateCount(value){return value.stages.reduce((total,stage)=>total+stage.candidates.length,0)}
function setSyncStatus(message){const note=document.querySelector('.save-note');if(note)note.textContent=message}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(isHydrating)return;clearTimeout(saveTimer);setSyncStatus('Salvando para todos...');saveTimer=setTimeout(pushSharedState,550)}
async function pushSharedState(){saveTimer=null;try{const response=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state})});if(!response.ok)throw new Error('Falha ao salvar');const data=await response.json();lastServerVersion=data.updatedAt||Date.now();setSyncStatus('✓ Disponível para todos')}catch(error){setSyncStatus('Sem conexão — tentando novamente');saveTimer=setTimeout(pushSharedState,3000)}}
async function pullSharedState(force=false){try{const response=await fetch(`/api/state?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error('Falha ao carregar');const data=await response.json();if(!data.state)return false;if(!force&&(saveTimer||document.activeElement?.matches('input,textarea')))return true;if((data.updatedAt||0)>lastServerVersion){state=normalizeState(data.state);lastServerVersion=data.updatedAt||Date.now();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}return true}catch(error){setSyncStatus('Sem conexão — dados salvos neste aparelho');return false}}
async function initialize(){const localState=loadState();state=localState;try{const response=await fetch(`/api/state?t=${Date.now()}`,{cache:'no-store'});const data=response.ok?await response.json():{};if(data.state){const migrate=!localStorage.getItem('shared-migration-v1')&&candidateCount(localState)>candidateCount(data.state);state=normalizeState(migrate?localState:data.state);lastServerVersion=data.updatedAt||0;localStorage.setItem('shared-migration-v1','done');isHydrating=false;render();if(migrate)await pushSharedState()}else{isHydrating=false;render();await pushSharedState()}}catch(error){isHydrating=false;render();setSyncStatus('Sem conexão — dados salvos neste aparelho')}setInterval(()=>pullSharedState(false),5000)}
function escapeHtml(v=''){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderRail(){rail.innerHTML=state.stages.map((s,i)=>`<button class="stage-button ${i===state.currentStage?'active':''}" role="tab" aria-selected="${i===state.currentStage}" data-stage="${i}"><span class="stage-copy"><span class="stage-title">${escapeHtml(s.title)}</span><span class="stage-date">${escapeHtml(s.date)||'Data a definir'}</span>${s.summary?`<span class="stage-summary">${escapeHtml(s.summary)}</span>`:''}</span><span class="lamp-wrap"><span class="lamp-number">${String(i+1).padStart(2,'0')}</span><span class="lamp"></span></span></button>`).join('');rail.querySelectorAll('.stage-button').forEach(b=>b.onclick=()=>{state.currentStage=Number(b.dataset.stage);save();render()})}
function renderWorkspace(){const s=state.stages[state.currentStage];const isInterview=s.dateSlots;workspace.innerHTML=`<button id="candidateGuide" class="candidate-guide" type="button" aria-label="Ir para os candidatos desta etapa"><span class="guide-arrow">↓</span><span>Clique aqui para ver candidatos desta etapa</span></button><div class="workspace-header"><div><span class="eyebrow">Etapa ${String(state.currentStage+1).padStart(2,'0')} de ${state.stages.length}</span><h2>${escapeHtml(s.title)}</h2></div><span class="status-pill">● Etapa atual</span></div><div class="workspace-grid"><div id="candidatesPanel" class="candidates-panel"><div class="panel-label">Candidatos</div><div id="candidateList" class="candidate-list"></div><button id="addCandidate" class="add-button">＋ Adicionar candidato</button></div><div class="editor-card"><div class="panel-label">Datas e registro</div><label class="field"><span>Data da etapa</span><input id="stageDate" placeholder="dd/mm/aaaa" value="${escapeHtml(s.date)}"></label>${isInterview?`<div><span class="panel-label">Datas de entrevistas</span><div id="interviewDates">${s.interviews.map((d,i)=>`<div class="interview-row"><input type="datetime-local" value="${escapeHtml(d)}" data-interview="${i}" aria-label="Data da entrevista ${i+1}"><button class="icon-button remove-interview" data-remove-interview="${i}" aria-label="Remover data">×</button></div>`).join('')}</div><button id="addInterview" class="add-button">＋ Adicionar outra data</button></div>`:''}<label class="field notes-field"><span>Registro da etapa</span><textarea id="stageNotes" placeholder="Escreva aqui decisões e próximos passos...">${escapeHtml(s.notes)}</textarea></label><p class="save-note">✓ Disponível para todos</p></div></div>`;
 document.querySelector('#candidateGuide').onclick=()=>document.querySelector('#candidatesPanel').scrollIntoView({behavior:'smooth',block:'center'});
 document.querySelector('#stageDate').oninput=e=>{s.date=e.target.value;save();renderRail()};document.querySelector('#stageNotes').oninput=e=>{s.notes=e.target.value;save()};document.querySelector('#addCandidate').onclick=()=>{s.candidates.push({name:'',link:'',status:'active',comments:''});save();renderCandidates()};
 if(isInterview){document.querySelector('#addInterview').onclick=()=>{s.interviews.push('');save();renderWorkspace()};document.querySelectorAll('[data-interview]').forEach(el=>el.oninput=e=>{s.interviews[Number(e.target.dataset.interview)]=e.target.value;save()});document.querySelectorAll('[data-remove-interview]').forEach(el=>el.onclick=()=>{s.interviews.splice(Number(el.dataset.removeInterview),1);save();renderWorkspace()})}renderCandidates();}
function renderCandidates(){const s=state.stages[state.currentStage],list=document.querySelector('#candidateList');if(!s.candidates.length){list.innerHTML='<div class="empty-state">Nenhum candidato nesta etapa.<br>Use o botão abaixo para começar.</div>';return}list.innerHTML='';s.candidates.forEach((candidate,index)=>{const node=document.querySelector('#candidateTemplate').content.cloneNode(true),card=node.querySelector('.candidate-card'),name=node.querySelector('.candidate-name'),link=node.querySelector('.candidate-link'),open=node.querySelector('.linkedin-open'),commentsButton=node.querySelector('.comments-button');name.value=candidate.name;link.value=candidate.link;open.href=candidate.link||'#';open.style.opacity=candidate.link?'1':'.35';commentsButton.classList.toggle('has-comments',Boolean(candidate.comments?.trim()));commentsButton.textContent=candidate.comments?.trim()?'Comentários ✓':'Comentários';if(candidate.status==='rejected'){card.classList.add('rejected');card.querySelector('.advance').remove();card.querySelector('.reject').remove();name.disabled=link.disabled=true}name.oninput=e=>{candidate.name=e.target.value;save()};link.oninput=e=>{candidate.link=e.target.value;open.href=e.target.value||'#';open.style.opacity=e.target.value?'1':'.35';save()};open.onclick=e=>{if(!candidate.link)e.preventDefault()};commentsButton.onclick=()=>openCandidateComments(index);card.querySelector('.advance')?.addEventListener('click',()=>advanceCandidate(index));card.querySelector('.reject')?.addEventListener('click',()=>{candidate.status='rejected';save();renderCandidates()});list.appendChild(node)})}
function openCandidateComments(index){const candidate=state.stages[state.currentStage].candidates[index];commentsCandidateIndex=index;commentsName.textContent=candidate.name||'Candidato sem nome';commentsTextarea.value=candidate.comments||'';commentsDialog.showModal();setTimeout(()=>commentsTextarea.focus(),50)}
document.querySelector('#saveComments').onclick=e=>{e.preventDefault();if(commentsCandidateIndex===null)return;const candidate=state.stages[state.currentStage].candidates[commentsCandidateIndex];candidate.comments=commentsTextarea.value.trim();save();renderCandidates();commentsDialog.close();commentsCandidateIndex=null}
document.querySelector('#closeComments').onclick=()=>{commentsCandidateIndex=null}
commentsDialog.addEventListener('click',e=>{if(e.target===commentsDialog){commentsDialog.close();commentsCandidateIndex=null}})
function advanceCandidate(index){if(state.currentStage>=state.stages.length-1)return;const [candidate]=state.stages[state.currentStage].candidates.splice(index,1);candidate.status='active';state.stages[state.currentStage+1].candidates.push(candidate);save();renderWorkspace()}
function bindSummary(){const title=document.querySelector('#jobTitle'),owner=document.querySelector('#owner');title.value=state.jobTitle;owner.value=state.owner;title.oninput=e=>{state.jobTitle=e.target.value;save()};owner.oninput=e=>{state.owner=e.target.value;save()}}
function render(){renderRail();renderWorkspace();bindSummary()}initialize();